# configuration file for dotnet-releaser
[msbuild]
project = "SwitchTubeDl/SwitchTubeDl.fsproj"
[github]
user = "panmau"
repo = "switchtube-dl"

[nuget]
publish = false

[brew]
home = "homebrew-panmau"

