# configuration file for dotnet-releaser
[msbuild]
project = "SwitchTubeDl/SwitchTubeDl.fsproj"
[github]
user = "panmau"
repo = "switchtube-dl"

[nuget]
publish = false

# TODO turn this on when repository is published
[brew]
publish = false
home = "homebrew-panmau"

