name: ci

on:
    push:
        paths-ignore:
            - 'README.md'
            - 'RELEASE.md'
            - 'CONTRIBUTING.md'
    pull_request:

jobs:
    build:
        runs-on: macos-latest

        steps:
            -   name: Checkout 🛎️
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Install .NET 6.0 🧳
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '6.0.x'

            -   name: Install dependencies 📦
                run: dotnet restore src

            -   name: Build project 🏗
                run: dotnet build src -c Release --no-restore

            -   name: Test 🏭
                run: dotnet run --project src/Tests

            -   name: Publish 🚀
                run: |
                    dotnet tool install --global dotnet-releaser --version "0.3.*"
                    dotnet-releaser publish --github-token ${{secrets.TOKEN_GITHUB}} src/dotnet-releaser.toml
